# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-14 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_auto_20171114_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player_lite',
            name='number',
            field=models.IntegerField(),
        ),
    ]
