# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-15 05:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_auto_20171114_0943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='number',
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
